### ISSUE TITLE
Dropdown doesn't scroll; doesn't show full multisite list

### ISSUE THREAD

**Issue by yorkaspacher** [DiscipleTools/disciple-tools-multisite-dropdown#2]
Whether on a page with few listings or on a page with many listings and the ability to scroll, the multisite dropdown list doesn't scroll, it stays fixed at screen height.

![image](https://user-images.githubusercontent.com/47872338/107602045-696fe600-6bf6-11eb-8b03-a6e5b355fc57.png)

![image](https://user-images.githubusercontent.com/47872338/107602121-886e7800-6bf6-11eb-8fa1-d4b40185ebbd.png)

**Comment by corsacca** [comment]
Great feedback @yorkaspacher !

**Comment by ChrisChasm** [comment]
Thanks @yorkaspacher . I fixed this and pushed a new release. https://github.com/DiscipleTools/disciple-tools-multisite-dropdown/releases/tag/1.2
